# Generated by Django 6.0.3 on 2026-03-25 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название блока (для админки)')),
                ('html_file', models.CharField(max_length=200, verbose_name='Путь к HTML (например, blocks/hero.html)')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название страницы (Title)')),
                ('slug', models.SlugField(blank=True, verbose_name='URL страницы (пусто = главная)')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('subdomain', models.CharField(max_length=100, unique=True, verbose_name='Поддомен (например, project1)')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Язык сайта')),
                ('color_main', models.CharField(default='#000000', max_length=20, verbose_name='Основной цвет')),
                ('color_accent', models.CharField(default='#FFFFFF', max_length=20, verbose_name='Акцентный цвет')),
                ('gsc_code', models.TextField(blank=True, verbose_name='Код Google Search Console')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода (0, 1, 2...)')),
                ('content_json', models.JSONField(blank=True, null=True, verbose_name='Контент (тексты, картинки)')),
                ('block_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.blocktemplate', verbose_name='Шаблон блока')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='builder.page', verbose_name='Страница')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='builder.site', verbose_name='Сайт'),
        ),
    ]
