# Generated by Django 6.0.3 on 2026-03-25 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocktemplate',
            options={'verbose_name': 'Шаблон блока', 'verbose_name_plural': 'Шаблоны блоков'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='pageblock',
            options={'ordering': ['order'], 'verbose_name': 'Блок на странице', 'verbose_name_plural': 'Блоки на странице'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Сайт', 'verbose_name_plural': 'Сайты'},
        ),
    ]
