# Generated by Django 6.0.3 on 2026-03-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='allowed_geos',
            field=models.CharField(default='ru', help_text='Например: ru, kz, lv, es', max_length=200, verbose_name='Разрешенные ГЕО (коды через запятую)'),
        ),
        migrations.AlterField(
            model_name='site',
            name='subdomain',
            field=models.CharField(max_length=100, unique=True, verbose_name='Поддомен'),
        ),
    ]
