# Generated by Django 6.0.3 on 2026-03-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_site_allowed_geos_alter_site_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocktemplate',
            name='default_content',
            field=models.JSONField(blank=True, help_text='Базовый текст на русском. Будет переведен автоматически.', null=True, verbose_name='Стандартный контент (JSON)'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('site', 'slug')},
        ),
    ]
