# Generated by Django 6.0.3 on 2026-03-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_blocktemplate_default_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='font_family',
            field=models.CharField(choices=[('Inter', 'Inter (Современный, чистый)'), ('Montserrat', 'Montserrat (Геометричный, стильный)'), ('Roboto', 'Roboto (Классический)'), ('Playfair Display', 'Playfair (Премиальный, с засечками)')], default='Inter', max_length=50, verbose_name='Шрифт сайта'),
        ),
        migrations.AddField(
            model_name='site',
            name='logo_text',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать название проекта', max_length=50, verbose_name='Текст логотипа'),
        ),
        migrations.AddField(
            model_name='site',
            name='rounded_corners',
            field=models.BooleanField(default=True, verbose_name='Скругленные углы дизайна'),
        ),
        migrations.AlterField(
            model_name='site',
            name='allowed_geos',
            field=models.CharField(default='ru', max_length=200, verbose_name='Разрешенные ГЕО'),
        ),
    ]
