# Generated by Django 6.0.3 on 2026-03-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_site_font_family_site_logo_text_site_rounded_corners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='icon_class',
            field=models.CharField(default='bi-file-earmark-text', help_text='Например: bi-house (Главная), bi-envelope (Контакты), bi-info-circle (О нас). Ищи на icons.getbootstrap.com', max_length=50, verbose_name='Иконка (Bootstrap Icon)'),
        ),
    ]
