# Generated by Django 6.0.3 on 2026-03-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_page_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Если пусто, возьмется название страницы + название сайта', max_length=200, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_image',
            field=models.CharField(blank=True, help_text='Вставьте URL картинки для превью в соцсетях/мессенджерах', max_length=500, verbose_name='Ссылка на картинку (OpenGraph)'),
        ),
    ]
