# Generated by Django 6.0.3 on 2026-03-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_page_meta_description_page_meta_title_page_og_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='block_images/', verbose_name='Изображение блока'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='image_position',
            field=models.CharField(choices=[('right', 'Картинка справа (на мобильном снизу)'), ('left', 'Картинка слева (на мобильном сверху)'), ('top', 'Картинка сверху (по центру)'), ('background', 'Картинка на фоне (с авто-затемнением)')], default='right', max_length=20, verbose_name='Расположение картинки'),
        ),
    ]
