# Generated by Django 6.0.3 on 2026-03-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_pageblock_image_pageblock_image_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocktemplate',
            name='html_code',
            field=models.TextField(blank=True, help_text='Вставьте HTML код прямо сюда. Поддерживаются теги Django.', null=True, verbose_name='HTML код блока'),
        ),
    ]
