# Generated by Django 6.0.3 on 2026-03-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0010_blocktemplate_html_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocktemplate',
            name='html_file',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Путь к HTML (Устарело)'),
        ),
    ]
