# Generated by Django 6.0.3 on 2026-03-29 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0011_alter_blocktemplate_html_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='footer_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Контент футера (JSON)'),
        ),
        migrations.AddField(
            model_name='site',
            name='footer_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='builder.blocktemplate', verbose_name='Шаблон Футера'),
        ),
        migrations.AddField(
            model_name='site',
            name='header_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Контент шапки (JSON)'),
        ),
        migrations.AddField(
            model_name='site',
            name='header_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='builder.blocktemplate', verbose_name='Шаблон Шапки'),
        ),
    ]
